### ISSUE TITLE
[Pet bar] bad bar position for in combat summoned pets (i.e. Shadowfiend, Water Elemental)

### ISSUE THREAD

**Issue by BennLiu** [trits/retail-ui#1]
Bro, the location of [Pet action bar] is too low,
would u plz fix that?
THX

**Comment by jelenv** [comment]
I don't have any issues with pet bar on hunter. But the addon has some bugs with pet bar position for some other pets (for example Mage water elemental). Can you send a screenshot on how it looks?

Can you describe it a bit more in detail? 

1. It is a pet used in combat or permanent one (hunter/warlock)?
2. Do you use Titan Panel Classic addon? there is an known issue that causes the action bars to shift a bit down
4. It's happening right after login or when does it happen? I would help me to have some process to reproduce it

**Comment by BennLiu** [comment]
The problem occurs when:
A Mage summon Water Elemental when he‘s already in combat。
like this [https://i.postimg.cc/YqfRGhft/1.jpg](https://i.postimg.cc/YqfRGhft/1.jpg)

![1](https://user-images.githubusercontent.com/10000498/190331219-66ba2de1-a4ba-4604-bf67-29a8e834b4a6.jpg)

**Comment by jelenv** [comment]
Ok, so it's the summon pet in combat action bar issue. Thanks. I'll try to solve it

**Comment by BennLiu** [comment]
thanks for your patience

**Comment by jelenv** [comment]
@RedJohnlol Is it still happening with latest version 3.0.3? I have improved and fixed pet bar positioning. I am just not sure if it affected the in-combat pets (did not test)

**Comment by BennLiu** [comment]
@trits The latest version 3.0.3 has already fixed the bug.
It works!  THANKS

**Comment by jelenv** [comment]
Glad to read that, I am closing the issue then.
