### ISSUE TITLE
can help me ? please

### ISSUE THREAD

**Issue by Lennrj** [trits/retail-ui#17]
![Sem título](https://github.com/trits/retail-ui/assets/112582848/0a72c7be-d847-4ed3-bb7b-ed17de1801ab)

petbar is bugged cant move this pls help

**Comment by jelenv** [comment]
I am not working on this anymore. I would recommend to find an alternative addon.

If you want to try to fix it yourself, modify the code in the file `retail-ui/RetailUI/RetailUI.lua` in function `Update_ActionBars`, and try to play with `petBar.x` and `petBar.y` values.

PS: this addon was last tested 2 years ago on WotLK Classic, something more recent may require more work to fix this.
