### ISSUE TITLE
Nice to have: Visual artifacts on bags and micromenu

### ISSUE THREAD

**Issue by Rzial** [trits/retail-ui#5]
As you can see in the following images:

![image](https://user-images.githubusercontent.com/332980/189489749-03d334e0-eb57-4033-ac01-9dc6d35aa189.png)
![image](https://user-images.githubusercontent.com/332980/189489855-de178349-c3c8-4bc4-983e-bc98bdaecc09.png)

There are three minor visual artifacts on the bag bar
* Tidy icons doesn't seem to affect the bag (big an small ones) icon
* Spacing is weird, you can see that the last bag icon background and the key holder doesn't adjust properly
* If 'Bag Space Text' option is enabled the text is showed twice.

There is a minor visual artifact on the micromenu
* The latecy bar is way bigger than the icond and is misplaced.

Also:
![image](https://user-images.githubusercontent.com/332980/189489962-41b64c59-82c0-424b-b95a-e4ae14f2cf91.png)

Eagles getting overrided by the bar feels a bit weird.

Additional information:
I play using a 21:9 resolution, maybe some of this report issues are related to that.

<3 Thank you for make it work for WotLK :D

Edit:
Found another artifact arround the third icon on the right bar:

![image](https://user-images.githubusercontent.com/332980/189490144-baf6d6e0-d5d1-427c-aef9-3fe489d46a48.png)

Doesn't seem to be related to the 'Tidy Icons' feature

**Comment by Rzial** [comment]
As said on the title this is just a nice to have thing. I would do a PR myself but to be honest I don't know anything about WoW AddOns development. Will take a look if this is not made in some time.

**Comment by jelenv** [comment]
Thanks for the detailed report. The performance bar issues started since last hotfix in classic. I'll try to fix these but you are welcome to do a PR :)

**Comment by jelenv** [comment]
I have released a new update 3.0.1, which fixes all of your points, apart from two:

- _Tidy icons doesn't seem to affect the bag (big an small ones) icon_: this is working correctly by design from original author, it's not implemented for bag icons.
- _Eagles getting overrided by the bar feels a bit weird:_ I don't see it as as issue. IMO the bar icons are more important and should be above the eagles. (No bug in addon, it's a design decision)

**Comment by jelenv** [comment]
What can be and hopefully will be improved is the background image for keyring. I did not have time for it yet

**Comment by Rzial** [comment]
Just tested it, feels perfect now, tyvm
