### ISSUE TITLE
dk stance and petbar overlap

### ISSUE THREAD

**Issue by boneodw** [trits/retail-ui#6]
dk stance and petbar overlap
![dk](https://user-images.githubusercontent.com/113349330/189635998-8e909656-7389-4e73-b805-629457fd87c9.jpg)

**Comment by jelenv** [comment]
Screenshot? What addon version? Conditions when it happens?
In Unholy with permanent ghoul it's working well for me

**Comment by boneodw** [comment]
added a screenshot version 3.0.2

**Comment by jelenv** [comment]
Thank you. I have some additional questions:
- Can you tell me what resolution do you play on and what UI scale? It could have an effect. 
- Do you have all the action bars enabled? 
- What does it look like with 3.0.1 for you? Please send screenshot if you can (of the whole action bars)

**Comment by boneodw** [comment]
UIScale is off, resolution: 1920 x 1080, only right bar is enabled.

as of 3.0.1, the petbar is completely shifted to the right of the other bars

**Comment by boneodw** [comment]
for example in the addon tidybar the stance bar is above the petbar

**Comment by jelenv** [comment]
thanks, I'll try to reproduce it. Do you have frost presence learned? On my DK I have it, and I don't see this problem (but I have UI scale at 0.75)

**Comment by boneodw** [comment]
with frostpresenc the problem persists.
with a lower scaling everything is ok

**Comment by jelenv** [comment]
Thanks very much, now I know what causes it.

**Comment by boneodw** [comment]
I am glad to help

**Comment by jelenv** [comment]
Should be fixed now in new version 3.0.3
