### ISSUE TITLE
[Pet bar] bad bar position when using Mind Control

### ISSUE THREAD

**Issue by tybaulk** [trits/retail-ui#7]
Hello! I play a Shadow Priest and whenever I Mind Control a mob there is a bug with the pet bar / Shadowform stance bar.

![image](https://user-images.githubusercontent.com/111405787/190252024-dc21b438-7b51-4a12-a72c-8c2ed82a1d8b.png)

Thank you for reviving this addon as I loved it but it had so many bugs with the pet bar.

**Comment by tybaulk** [comment]
Something like this: 

![image](https://user-images.githubusercontent.com/111405787/190254147-6f30b14a-3d95-482f-84a2-45db50100b20.png)

I know it's probably frivolous and OCD of me.

**Comment by jelenv** [comment]
Thanks for the report, I'll try to fix it.
What is the bar under shadowform on the screenshot? If you can, please turn on `/fstack` in chat and hover over it, then please send me a screenshot of what it says about it (or write it here). You can turn off `/fstack` by writing `/reload`.
