### ISSUE TITLE
Both action bars dropping down

### ISSUE THREAD

**Issue by Lucrona** [trits/retail-ui#8]
Just on one character, Alliance mage.

Both acction bars will move down and half overlap, UI graphics will stay the same
![Screenshot 2022-09-18 091954](https://user-images.githubusercontent.com/113807308/190879371-e1defad3-df21-47b5-86f2-224d6670363b.png)

it fixes itself if i go in combat and then out or if i click show bottom left/right action bars in WoW interface options

**Comment by jelenv** [comment]
Thanks for the report, For now I don't have a fix yet. It happens together with Titan Panel Classic addon. 
As a workaround you can fix it by:
- **Turn off any Bottom Bars** in Titan and also **turn on "Disable Screen Adjust" for bottom bars** in Titan. 
- You might also need to turn on "Disable Screen Adjust" for top bars (I have not tested this).
